cluster:
  name: es

index:
  analysis:
    analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true

path:
  data: /mnt/es/data
  logs: /mnt/es/log

bootstrap:
  memory_lock: true

http:
  enabled: true
  compression: true
    
script:
    disable_dynamic: false
